apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: issues-operator
    app.kubernetes.io/managed-by: kustomize
  name: issues-operator-system
