---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - training.redhat.com
  resources:
  - githubissues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.redhat.com
  resources:
  - githubissues/finalizers
  verbs:
  - update
- apiGroups:
  - training.redhat.com
  resources:
  - githubissues/status
  verbs:
  - get
  - patch
  - update
